//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrowaveConverter.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrowaveConverter.Resources.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microwave Converter.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Time.
        /// </summary>
        internal static string OriginalTime {
            get {
                return ResourceManager.GetString("OriginalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many watts are indicated on the packaging?.
        /// </summary>
        internal static string OriginalTimeQuestion {
            get {
                return ResourceManager.GetString("OriginalTimeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Wattage.
        /// </summary>
        internal static string OriginalWattage {
            get {
                return ResourceManager.GetString("OriginalWattage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long should the food be heated according to the packaging?.
        /// </summary>
        internal static string OriginalWattageQuestion {
            get {
                return ResourceManager.GetString("OriginalWattageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Time.
        /// </summary>
        internal static string TargetTime {
            get {
                return ResourceManager.GetString("TargetTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Wattage.
        /// </summary>
        internal static string TargetWattage {
            get {
                return ResourceManager.GetString("TargetWattage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With how many watts should the food be heated?.
        /// </summary>
        internal static string TargetWattageQuestion {
            get {
                return ResourceManager.GetString("TargetWattageQuestion", resourceCulture);
            }
        }
    }
}
